### ISSUE TITLE
Type definition file 'index.d.ts' is missing jsdoc for methods

### ISSUE THREAD

**Issue by xy1xy** [datalust/seq-logging#42]
**AC:**
As a developer using VSCode (or any TS-aware IDE), I would like the intellisense for functions and class methods (e.g. `seq_logger.js`) to be displayed with the accompanying comments/jsdocs. This will save me having to look into the source code for definitions, e.g. what is the difference between _flush_ and _flushToBeacon_

**Notes:**
The package `seq-logging` definition file (`node_modules/seq-logging/index.d.ts`) does not have the SeqLogger method comments.

I think perhaps this problem is two-fold:

1. The methods on `node_modules/seq-logging/seq_logger.js` are not using the [jsdoc](https://jsdoc.app/) format
2. The type definition file generation process (`tsc index.js --declaration --emitDeclarationOnly`) should then be run

**Comment by nblumhardt** [comment]
Thanks for the heads-up! 👍

**Comment by xy1xy** [comment]
I'll get a PR up for this by the end of next week - otherwise bump me for a reminder

**Comment by xy1xy** [comment]
Related PR: https://github.com/datalust/seq-logging/pull/44

**Comment by nblumhardt** [comment]
Fixed in #44
