### ISSUE TITLE
Version 2.1.0 is missing all code content outside of `index.js`

### ISSUE THREAD

**Issue by markacola** [datalust/seq-logging#74]
The recently published version doesn't package the code correctly, e.g. missing the `seq_logger.js` file that is imported via `index.js`:
https://www.npmjs.com/package/seq-logging?activeTab=code

The code is published and working correctly for earlier versions, e.g.:
https://www.npmjs.com/package/seq-logging/v/2.0.0?activeTab=code

**Comment by liammclennan** [comment]
Hi @markacola 

Thank you for the report. `2.1.1` has the missing files.

**Comment by markacola** [comment]
Fantastic - thank you for the speedy resolution!
