### ISSUE TITLE
Add support for typescript nad Vite.js

### ISSUE THREAD

**Issue by StefanoMigotto** [datalust/seq-logging#84]
I try add the seq package for my project (React.JS + Vite.js + typescript) but not working, i have try with the seq package and the bunyan package but not working, the seq package have problem caused by process.env (on vite.js .env not used) and the bunyan: 

X [ERROR] Could not resolve require("./src/build/**/*/DTraceProviderBindings")

    node_modules/dtrace-provider/dtrace-provider.js:18:30:
      18 │         var binding = require('./src/build/' + builds[i] + '/DTraceProviderBindings');
         ╵                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by KodrAus** [comment]
Hi @StefanoMigotto :wave: Did you end up resolving this in the end?
